CREATE DATABASE BankingSystem;

USE BankingSystem; 

CREATE TABLE Accounts (
  id INT PRIMARY KEY AUTO_INCREMENT,
  username VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL
);  

